# Generated by Django 3.2.14 on 2022-08-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('project_name', models.CharField(max_length=124, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('project_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Project link')),
                ('project_workers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Workers')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created', 'project_name'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('note_header', models.CharField(max_length=64, null=True, verbose_name='Header')),
                ('note_text', models.CharField(max_length=255, verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activity')),
                ('note_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TASK.project', verbose_name='Note project')),
                ('note_worker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Note creator')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
