# Generated by Django 3.2.14 on 2022-09-07 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TASK', '0002_alter_todo_note_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='project_managers', to=settings.AUTH_USER_MODEL, verbose_name='Managers'),
        ),
    ]
