# Generated by Django 3.2.14 on 2022-09-07 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TASK', '0003_project_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_workers',
        ),
        migrations.AddField(
            model_name='project',
            name='project_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creators'),
        ),
    ]
